# Generated by Django 4.0.3 on 2022-03-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0002_alter_register_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='hour_exit',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='totals',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
