# Generated by Django 4.0.3 on 2022-03-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0008_alter_register_hour_entry_alter_register_hour_exit'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='minutes',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
